<a href="https://colab.research.google.com/github/Sheila-Otieno/Python-mini-projects/blob/main/Hangman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import additional functions
from random import choice
from IPython.display import clear_output

In [ ]:
# declare game variables
words = [ "tree", "basket", "chair", "paper", "python" ]
word = choice(words)     # randomly chooses a word from words list
guessed, lives, game_over = [ ], 7, False   # multi variable assignment

In [ ]:
# create a list of underscores to the length of the word
guesses = [ "_ " ] * len(word)


In [ ]:
# create main game loop
while not game_over:
          ans = input("Type quit or guess a letter: ").lower( )
          if ans == "quit":
              print("Thanks for playing.")
          game_over = True

In [ ]:
# create main game loop
while not game_over:
    # output game information
    hidden_word = ''.join(guesses)
    print('Your guessed letters: {}'.format(guessed))
    print('Word to guess: {}'.format(hidden_word))
    print('Lives: {}'.format(lives))
    
    ans = input('Type quit or guess a letter: ').lower()
    
    clear_output()     # clear all previous output
    
    if ans == 'quit':
        print('Thanks for playing.')
        game_over = True
    elif ans in word and ans not in guessed:
        print('You guessed correctly!')
        
        # create a loop to change underscore to proper letter
        for i in range(len(word)):
            if word[i] == ans:
                guesses[i] = ans
    elif ans in guessed:
        print('You already guessed that. Try again.')
    else:                 # otherwise lose life
        lives -= 1
        print('Incorrect, you lost a life.')
        
    if ans not in guessed:
        guessed.append(ans)    # add guess to guessed list
        
    if lives <= 0:
        print('You lost all your lives, you lost!')
        game_over = True
    elif word == ''.join(guesses):
        print('Congratulations, you guessed it correctly!')
        game_over = True

In [ ]:
# declare game variables
words = ['tree', 'basket', 'chair', 'paper', 'python']
word = choice(words)
guessed, lives, game_over = [], 7, False

# create a list of underscores to the length of the word
guesses = ['_ '] * len(word)

# create main game loop
while not game_over:
    # output game information
    hidden_word = ''.join(guesses)
    print('Your guessed letters: {}'.format(guessed))
    print('Word to guess: {}'.format(hidden_word))
    print('Lives: {}'.format(lives))
    
    ans = input('Type quit or guess a letter: ').lower()
    
    clear_output()     # clear all previous output
    
    if ans == 'quit':
        print('Thanks for playing.')
        game_over = True
    elif ans in word and ans not in guessed:
        print('You guessed correctly!')
        
        # create a loop to change underscore to proper letter
        for i in range(len(word)):
            if word[i] == ans:
                guesses[i] = ans
    elif ans in guessed:
        print('You already guessed that. Try again.')
    else:                 # otherwise lose life
        lives -= 1
        print('Incorrect, you lost a life.')
        
    if ans not in guessed:
        guessed.append(ans)    # add guess to guessed list
        
    if lives <= 0:
        print('You lost all your lives, you lost!')
        game_over = True
    elif word == ''.join(guesses):
        print('Congratulations, you guessed it correctly!')
        game_over = True


You guessed correctly!
Congratulations, you guessed it correctly!


In [ ]:
#Pyramids: Use a for loop to build a pyramid of x's. It should be modular so that if you loop to 5 or 50, it still creates evenly spaced rows. Hint: Multiply the string 'x' by the row. For example, 
#if you loop to the range of 4, it should produce the following result:

In [ ]:
row = 15

for i in range(row):
    print(' ' * (row - i) + ' x' * i)

               
               x
              x x
             x x x
            x x x x
           x x x x x
          x x x x x x
         x x x x x x x
        x x x x x x x x
       x x x x x x x x x
      x x x x x x x x x x
     x x x x x x x x x x x
    x x x x x x x x x x x x
   x x x x x x x x x x x x x
  x x x x x x x x x x x x x x


In [ ]:
import numpy as np
import random


a = random.sample(range(1, 10), 4)
b = random.sample(range(1, 10), 4)
c = random.sample(range(1, 10), 4)
list1= np.array([a,b,c])
print(list1)


f = random.sample(range(1, 10), 4)
g = random.sample(range(1, 10), 4)
h = random.sample(range(1, 10), 4)

list2 = np.array([f,g,h])
print(list2)

#Addition
sumoflists = list1 + list2
print("sum")
print(sumoflists)

#subtraction
suboflists = list1 - list2
print("sub")
print(suboflists)

#Multiplication
multoflists = list1 * list2
print("multiplication")
print(multoflists)

[[8 9 6 2]
 [9 5 4 3]
 [1 4 7 5]]
[[1 4 7 5]
 [8 1 9 7]
 [5 6 3 7]]
sum
[[ 9 13 13  7]
 [17  6 13 10]
 [ 6 10 10 12]]
sub
[[ 7  5 -1 -3]
 [ 1  4 -5 -4]
 [-4 -2  4 -2]]
multiplication
[[ 8 36 42 10]
 [72  5 36 21]
 [ 5 24 21 35]]


In [ ]:
import pandas as pd

a = random.sample(range(0, 100), 100)
b = random.sample(range(0, 100), 100)
c = random.sample(range(0, 100), 100)
list = [a,b,c]

listdf = pd.DataFrame(list, dtype = int)
listdf.head()

0   1   2   3   4   5   6   7   8   ...  91  92  93  94  95  96  97  98  99
0  56  61  57  30  69   1   3  58  73  ...  74  12  60  33   0  59  48  87  44
1  46  16  81  60  40  53  93  32  96  ...   9  88  76  11  10  68  33  25  30
2  70   1  32  90   7  96  58  76  24  ...  60  29  13  50  93  22  46  40  80

[3 rows x 100 columns]

In [ ]:
# import additional functions
from random import choice
from IPython.display import clear_output


def checkGameCondition(lives, guesses, word):
    if lives <= 0:
        print('You lost all your lives, you lost!')
        return True
    elif word == ''.join(guesses):
        print('Congratulations, you guessed it correctly!')
        return True
        
    return False

def checkGuess(ans, word, guesses, guessed, lives):
    game_over = False
    
    if ans == 'quit':
        print('Thanks for playing.')
        game_over = True
    elif ans in word and ans not in guessed:
        print('You guessed correctly!')

        # create a loop to change underscore to proper letter
        for i in range(len(word)):
            if word[i] == ans:
                guesses[i] = ans
    elif ans in guessed:
        print('You already guessed that. Try again.')
    else:                 # otherwise lose life
        lives -= 1
        print('Incorrect, you lost a life.')

    if ans not in guessed:
        guessed.append(ans)    # add guess to guessed list
        
    return game_over, guesses, guessed, lives

def outputGameInfo(guesses, guessed, lives):
    hidden_word = ''.join(guesses)
    print('Your guessed letters: {}'.format(guessed))
    print('Word to guess: {}'.format(hidden_word))
    print('Lives: {}'.format(lives))



def gamePlay():
    # declare game variables
    words = ['tree', 'basket', 'chair', 'paper', 'python']
    word = choice(words)
    guessed, lives, game_over = [], 7, False

    # create a list of underscores to the length of the word
    guesses = ['_ '] * len(word)

    # create main game loop
    while not game_over:
        # output game information
        outputGameInfo(guesses, guessed, lives)

        ans = input('Type quit or guess a letter: ').lower()

        clear_output()     # clear all previous output

        game_over, guesses, guessed, lives = checkGuess(ans, word, guesses, guessed, lives)

        game_over = checkGameCondition(lives, guesses, word)
            
gamePlay()

You guessed correctly!
Congratulations, you guessed it correctly!
